// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/basic/Button.vue')['default']
    copy: typeof import('./src/components/basic/Button copy.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogDescription: typeof import('@headlessui/vue')['DialogDescription']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    EntityAdd: typeof import('./src/components/Entity/EntityAdd.vue')['default']
    EntityItem: typeof import('./src/components/Entity/EntityItem.vue')['default']
    EntityList: typeof import('./src/components/Entity/EntityList.vue')['default']
    Input: typeof import('./src/components/basic/Input.vue')['default']
    List: typeof import('./src/components/basic/List.vue')['default']
    Modal: typeof import('./src/components/basic/Modal.vue')['default']
    RelationAdd: typeof import('./src/components/Relation/RelationAdd.vue')['default']
    RelationItem: typeof import('./src/components/Relation/RelationItem.vue')['default']
    RelationList: typeof import('./src/components/Relation/RelationList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
